#!/bin/bash
water_decimal=$(echo "ibase=water; ${WATER}" | bc); stir_decimal=$(echo "ibase=stir; ${STIR}" | bc); result_decimal=$((water_decimal + stir_decimal)); result_bestchol=$(echo "obase=bestchol; ${result_decimal}" | bc); echo "The result is: ${result_bestchol}"

